
# base host which will be used as a base domain
# for different services
baseHost: ""

# Control Plane API parameters
api:
  image: wafieio/api:latest
  svc:
    name: wafie-api
    port: 80

# Discover Agent parameters
discoveryAgent:
  image: wafieio/api:latest

# Application Security Gateway parameters
gateway:
  ads: wafieio/gateway:latest
  proxy: envoyproxy/envoy:v1.36.2
  xproc: wafieio/xproc:latest

# Relay parameters
relay:
  image: wafieio/relay:latest

console:
  enabled: true
  image: docker.io/wafieio/console:latest


# Shared configurations
config:
  apiAddr: ""


# postgresql configurations
postgresql:
  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/postgresql
  auth:
    postgresPassword: "cwafpg"
    username: "cwafpg"
    password: "cwafpg"
    database: "cwaf"
  primary:
    persistence:
      size: 20Gi
  volumePermissions:
    enabled: false

opensearch:
  singleNode: true
  opensearch.yml: |
    cluster.name: opensearch-cluster
    network.host: 0.0.0.0
  extraEnvs:
    - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
      value: 8NybEHCU81IzgWhx
  persistence:
    enabled: true
