apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: {{.Release.Namespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
        - image: {{.Values.image}}
          imagePullPolicy: IfNotPresent
          name: httpbin
          ports:
            - containerPort: 8080
