apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpbin
  namespace: {{.Release.Namespace}}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: "{{.Values.host}}"
      http:
        paths:
          - backend:
              service:
                name: httpbin
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - "{{.Values.host}}"
      secretName: charts-cert