{{if .Values.console.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: wafie-console-config
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.api.ingress.enabled }}
    {{- if .Values.api.ingress.tls}}
  WAFIE_API_HOST: "https://{{.Values.api.ingress.host}}"
    {{- else}}
  WAFIE_API_HOST: "http://{{.Values.api.ingress.host}}"
    {{- end }}
  {{- else }}
  WAFIE_API_HOST: "http://{{.Values.api.svc.name}}.{{.Release.Namespace}}.svc"
  {{- end }}
{{- end }}