{{if .Values.console.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: wafie-console-config
  namespace: {{ .Release.Namespace }}
data:
  # WAFie API - Internal K8s service URL
  WAFIE_API_URL: "http://{{.Values.api.svc.name}}.{{.Release.Namespace}}.svc"
{{- end }}