{{if .Values.console.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wafie-console
  namespace: {{.Release.Namespace}}
  annotations: {{ .Values.console.ingress.annotations | toJson }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{.Values.console.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wafie-console
                port:
                  number: 3000
{{- if .Values.console.ingress.tls }}
  tls:
    - hosts:
        - "{{ .Values.console.ingress.host }}"
      secretName: wafie-console-certs
{{- end }}
{{- end }}