FROM dimssss/modsec-debian as libwafie

FROM debian:bookworm-slim
ARG ARCH
ENV GO_VERSION="go1.25.4.linux-${ARCH}.tar.gz"
ENV GOBIN="/go/bin"
ENV PATH="${PATH}:${GOBIN}:/usr/local/go/bin"
ENV GOPATH="/go"
WORKDIR /go/src
RUN apt -y update \
    && apt -y install \
      libxml2-dev \
      libyajl-dev \
      libgeoip-dev \
      libcurl4-openssl-dev \
      gcc \
      vim \
      wget \
      unzip
RUN wget "https://go.dev/dl/${GO_VERSION}" \
    && tar -C /usr/local -xzf ${GO_VERSION} \
    && rm ${GO_VERSION}
COPY --from=libwafie /wafie/build/libwafie.so /usr/local/lib/libwafie.so
COPY --from=libwafie /wafie/build/test_hello /usr/local/bin/test_hello
COPY xproc/pkg/modsec/config/ /config
COPY xproc/pkg/modsec/include/ /usr/local/include
RUN ldconfig