FROM bufbuild/buf AS protobuf-builder
WORKDIR /app
ADD ../api ./api
RUN --mount=type=secret,id=buf_auth_token \
    export BUF_TOKEN=$(cat /run/secrets/buf_auth_token) \
    && cd api \
    && buf dep update \
    && buf lint \
    && buf generate

FROM golang:1.25.4-bookworm AS builder
WORKDIR /app
COPY ../logger ./logger
COPY ../go.mod go.sum ./
COPY ../Makefile Makefile
COPY --from=protobuf-builder /app/api ./api
COPY relay/cmd/ relay/cmd
COPY relay/pkg relay/pkg
RUN make relay

FROM debian:bookworm-slim
RUN apt -y update \
    && apt -y install \
              socat \
              nftables
COPY --from=builder /app/.bin/wafie-relay /usr/local/bin/wafie-relay


